name: Deploy on EC2 Instance

on:
  push:
    branches:
      - aws

jobs:
  deploy:
    runs-on: self-hosted
    name: Build and Deploy on EC2 via SSH

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build .NET Application
      run: |
        dotnet restore
        dotnet publish -c Release -o ./publish

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa

    - name: Add EC2 Host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Copy files to EC2 instance
      run: |
        scp -r ./publish/* ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/var/www/UserManagerAPI/

    - name: Restart application on EC2 instance
      run: |
        ssh ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} 'sudo systemctl restart kestrel-usermanager.service'
