name: Deploy on Huawei-WSL Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Build and Deploy on Huawei-WSL

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build .NET Application
      run: |
        dotnet restore
        dotnet publish -c Release -o ./publish

    - name: Deploy and Run Application
      run: |
        sudo systemctl stop kestrel-usermanager.service
        cp -r ./publish/* /var/www/UserManagerAPI/
        sudo systemctl start kestrel-usermanager.service
