name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy to Huawei-WSL Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build .NET Application
      run: |
        dotnet restore
        dotnet publish -c Release -o ./publish

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2's IP to known_hosts
      run: ssh-keyscan -H ${{ secrets.AWS_EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        scp -r ./publish/* ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/var/www/UserManagerAPI/publish
        ssh ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
          sudo systemctl restart kestrel-usermanager.service
        EOF
