name: Deploy on Huawei-WSL Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Build and Deploy on Huawei-WSL

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build .NET Application
      run: |
        dotnet restore
        dotnet publish -c Release -o ./publish

    - name: Copy files to target directory
      run: |
        sudo mkdir -p /var/www/UserManagerAPI
        sudo cp -r ./publish/* /var/www/UserManagerAPI/

    - name: Restart the application
      run: |
        sudo systemctl restart kestrel-usermanager.service
